name: demo action push event
on: push
jobs:
  first-job:
    runs-on: ubuntu-latest
    steps:
      - name: print greeting
        run: echo "Hellow World"
      - name: GoodBye
        run: echo "Good Bye"
    
