name: my-demo-1st-workflow
on: workflow_dispatch
jobs:
  first-job: 
    runs-on: ubuntu-latest
    steps:
      - name: print greeting
        run: echo "Hello World"
      - name: print goodBye
        run: echo "Done Bye"
